### ISSUE TITLE
Does integration work with HA 2026.2 and higher?

### ISSUE THREAD

**Issue by szymonsmolka** [tykarol/home-assistant-viomi-vacuum-v8#14]
After updating HA to version 2026.2 or higher, the integration disappears. Is it no longer supported?

**Comment by nexpspace** [comment]
Does also not work for me.

Error log:

```
Logger: homeassistant.config
Quelle: config.py:1082
Erstmals aufgetreten: 01:01:03 (1 Vorkommnis)
Zuletzt protokolliert: 01:01:03
Platform error: vacuum - cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1082, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1116, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1106, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1280, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1312, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/viomi_vacuum_v8/vacuum.py", line 9, in <module>
    from homeassistant.components.vacuum import (
    ...<9 lines>...
    )
ImportError: cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)
```

**Comment by szymonsmolka** [comment]
> Does also not work for me.

I switched to twin integration:

https://github.com/diogocaseca/home-assistant-viomi-vacuum-v8

It works for now.

**Comment by nexpspace** [comment]
> > Does also not work for me.
> 
> I switched to twin integration:
> 
> https://github.com/diogocaseca/home-assistant-viomi-vacuum-v8
> 
> It works for now.

This worked for me, thank you!
